# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terraform-state"
    key                  = "environments/daily/us/resource-group/terraform.tfstate"
    resource_group_name  = "rg-shared-eus2"
    storage_account_name = "assdteus2016st001"
    subscription_id      = "61407a28-a2f5-4d0d-86da-6af06fb1ef92"
  }
}
